name: Docker Compose Actions Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_PASSWORD: "test"
          POSTGRES_USER: "test"
          POSTGRES_DB: "test"
      redis:
        image: redis
      kafka:
        image: spotify/kafka
        env:
          ADVERTISED_HOST: "localhost"
          ADVERTISED_PORT: "9092"
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: "test"
          MONGO_INITDB_ROOT_PASSWORD: "test"
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Test1234"
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: "test"
          MYSQL_DATABASE: "test"
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        env:
          path.repo: "/tmp"
          repositories.url.allowed_urls: "http://*"
          bootstrap.memory_lock: "false"
          node.name: "test"
          cluster.initial_master_nodes: "test"
          discovery.zen.ping.unicast.hosts: "elasticsearch"
          http.max_content_length: "5mb"
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        options: --name minio-server
      rabbit:
        image: rabbitmq:3.7.18-management
        volumes:
          - ./test/rabbit-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
          - ./test/rabbit-config/ca_certificate.pem:/etc/rabbitmq/certs/ca_certificate.pem
          - ./test/rabbit-config/server_certificate.pem:/etc/rabbitmq/certs/server_certificate.pem
          - ./test/rabbit-config/server_key.pem:/etc/rabbitmq/certs/server_key.pem

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install msodbcsql17
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list -o /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install msodbcsql17 unixodbc-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "file://`pwd`#egg=catcher[compose]"
      - name: Test with pytest
        run: |
          pytest
